# hash:sha256:64776c9f58a5c9b9aefc187d701f9c6840104ad7d93d8f71820cef2d389942bc
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/omix-r-seurat-conversion:r4.4.3-v1

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ASKPASS
COPY git-ask-pass /
