# hash:sha256:af8329c48cf1a77f03b7274e5debb0df3b898a993ec4682e6547a654ef2ea6c6
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/omix-r-seurat-conversion:r4.4.3-v2

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ASKPASS
COPY git-ask-pass /
